### ISSUE TITLE
Unpickling error

### ISSUE THREAD

**Issue by B0WANG0** [woctezuma/SimSwap-colab#1]
Not a coder by trade, I had it working for a while with great results but now it won't run.
Getting this error every time I run Official Code:

UnpicklingError                           Traceback (most recent call last)
[<ipython-input-86-759c1f6ba011>](https://localhost:8080/#) in <module>()
     13 
     14 torch.nn.Module.dump_patches = True
---> 15 model = create_model(opt)
     16 model.eval()
     17 

3 frames
[/content/SimSwap/models/models.py](https://localhost:8080/#) in create_model(opt)
     16         model = UIModel()
     17 
---> 18     model.initialize(opt)
     19     if opt.verbose:
     20         print("model [%s] was created" % (model.name()))

[/content/SimSwap/models/fs_model.py](https://localhost:8080/#) in initialize(self, opt)
     62         # Id network
     63         netArc_checkpoint = opt.Arc_path
---> 64         netArc_checkpoint = torch.load(netArc_checkpoint)
     65         self.netArc = netArc_checkpoint['model'].module
     66         self.netArc = self.netArc.to(device)

[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in load(f, map_location, pickle_module, **pickle_load_args)
    606                     return torch.jit.load(opened_file)
    607                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 608         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    609 
    610 

[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    775             "functionality.")
    776 
--> 777     magic_number = pickle_module.load(f, **pickle_load_args)
    778     if magic_number != MAGIC_NUMBER:
    779         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.

**Comment by woctezuma** [comment]
There must be an issue with the model file (google drive on cool-down, corrupt download, etc.). Same issue as in:
- https://github.com/neuralchen/SimSwap/issues/35

**Comment by paulchui123** [comment]
I have similar error when I run Official Code every time, i can't find solution anywhere

/content/SimSwap
Traceback (most recent call last):
  File "test_wholeimage_swapsingle.py", line 35, in <module>
    model = create_model(opt)
  File "/content/SimSwap/models/models.py", line 18, in create_model
    model.initialize(opt)
  File "/content/SimSwap/models/fs_model.py", line 64, in initialize
    netArc_checkpoint = torch.load(netArc_checkpoint)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by woctezuma** [comment]
Alright, I can reproduce the issue in Google Colab.

```bash
%cd /content/SimSwap
%mkdir -p /content/output/single/

!python test_wholeimage_swapsingle.py \
 --isTrain false  --name people \
 --Arc_path arcface_model/arcface_checkpoint.tar \
 --pic_a_path {jpg_input} \
 --pic_b_path {jpg_output} \
 --output_path /content/output/single/ > /dev/null
```

```
/content/SimSwap
Traceback (most recent call last):
  File "test_wholeimage_swapsingle.py", line 35, in <module>
    model = create_model(opt)
  File "/content/SimSwap/models/models.py", line 18, in create_model
    model.initialize(opt)
  File "/content/SimSwap/models/fs_model.py", line 64, in initialize
    netArc_checkpoint = torch.load(netArc_checkpoint)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by woctezuma** [comment]
Fixed with new download locations.
