### ISSUE TITLE
Simswap not works 

### ISSUE THREAD

**Issue by nascacorp** [woctezuma/SimSwap-colab#14]
Getting an error with two Simswap collab (pictures/videos)

**Comment by woctezuma** [comment]
What is the error message?

Edit: Copied below: `ValueError: This ORT build has...`

```
Traceback (most recent call last):
  File "/content/SimSwap/test_wholeimage_swapsingle.py", line 55, in <module>
    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
  File "/content/SimSwap/insightface_func/face_detect_crop_single.py", line 40, in __init__
    model = model_zoo.get_model(onnx_file)
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 56, in get_model
    model = router.get_model()
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 23, in get_model
    session = onnxruntime.InferenceSession(self.onnx_file, None)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
```

```
Traceback (most recent call last):
  File "/content/SimSwap/test_wholeimage_swapmulti.py", line 56, in <module>
    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
  File "/content/SimSwap/insightface_func/face_detect_crop_multi.py", line 40, in __init__
    model = model_zoo.get_model(onnx_file)
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 56, in get_model
    model = router.get_model()
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 23, in get_model
    session = onnxruntime.InferenceSession(self.onnx_file, None)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
```

**Comment by woctezuma** [comment]
A priori, it is easy to fix, but it should be done in the official repositories of SimSwap or insightface.

Related:
- https://github.com/neuralchen/SimSwap/issues/445
- https://github.com/neuralchen/SimSwap/issues/316#issuecomment-1250162152

**Comment by woctezuma** [comment]
I can confirm that editing the following file inside `insightface` works.

```
File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 23
```

```diff
    def get_model(self):
-        session = onnxruntime.InferenceSession(self.onnx_file, None)
+        session = onnxruntime.InferenceSession(self.onnx_file, None, providers=['AzureExecutionProvider', 'CPUExecutionProvider'])
```

**Comment by woctezuma** [comment]
```bash
!pip install -U insightface
```

Upgrading `insightface` works as well, but leads to another issue with `SimSwap`.

```
Traceback (most recent call last):
  File "/content/SimSwap/test_wholeimage_swapsingle.py", line 62, in <module>
    img_a_align_crop, _ = app.get(img_a_whole,crop_size)
  File "/content/SimSwap/insightface_func/face_detect_crop_single.py", line 64, in get
    bboxes, kpss = self.det_model.detect(img,
TypeError: RetinaFace.detect() got an unexpected keyword argument 'threshold'
```

- https://github.com/neuralchen/SimSwap/issues/139

**Comment by woctezuma** [comment]
To summarize, the following happens with `insightface==0.6.2` or below.

```
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
```

---

The following happens with `insightface==0.7` or above.

```
TypeError: RetinaFace.detect() got an unexpected keyword argument 'threshold'
```

---

The version history is at https://pypi.org/project/insightface/#history

**Comment by woctezuma** [comment]
Fixed for now with [a fork of SimSwap](https://github.com/woctezuma/SimSwap/tree/upgrade-insightface) which [removes](https://github.com/woctezuma/SimSwap/commit/061329137d6d978d44ae2dc7c4700b825180c2ea) the threshold for Retinaface.
- https://github.com/woctezuma/SimSwap-colab/commit/074a71b9211bcb7e63a4517c80345711c7d6ae53 `Upgrade insightface to version 0.7.3 `
- https://github.com/woctezuma/SimSwap-colab/commit/21f45b26a61930bf114a0050bff0cce6c93707e5 `Rely on my fork of SimSwap `

See that there is [indeed](https://github.com/deepinsight/insightface/blob/c2db41402c627cab8ea32d55da591940f2258276/python-package/insightface/model_zoo/retinaface.py#L207) no 'threshold' argument:
```python
class RetinaFace:
    def detect(self, img, input_size = None, max_num=0, metric='default'):
```

**Comment by nascacorp** [comment]
Working now! thanks a lot pal

**Comment by woctezuma** [comment]
You are welcome! Thank you for reporting this issue!

---

Regarding my solution, I had the choice between fixing:
- `ValueError: This ORT build has...`,
- `TypeError: RetinaFace.detect() got ...`.

I went with the latter and I believe there should be no issue with this solution. Indeed:

1. the [default value](https://github.com/deepinsight/insightface/blob/c2db41402c627cab8ea32d55da591940f2258276/python-package/insightface/model_zoo/retinaface.py#L84) of `self.det_thresh` is the same (0.5):

```python
class RetinaFace:
    def __init__(self, model_file=None, session=None):
        self.det_thresh = 0.5
```

vs. [inside SimSwap](https://github.com/woctezuma/SimSwap/blob/061329137d6d978d44ae2dc7c4700b825180c2ea/insightface_func/face_detect_crop_single.py#L51-L52):

```python
class Face_detect_crop:
    def prepare(self, ctx_id, det_thresh=0.5, det_size=(640, 640), mode ='None'):
        self.det_thresh = det_thresh
```

2. `self.det_thresh` is directly used [inside `detect()`](https://github.com/deepinsight/insightface/blob/c2db41402c627cab8ea32d55da591940f2258276/python-package/insightface/model_zoo/retinaface.py#L224):

```python
    def detect(self, img, input_size = None, max_num=0, metric='default'):
        scores_list, bboxes_list, kpss_list = self.forward(det_img, self.det_thresh)
```

without [the need to specify the variable](https://github.com/woctezuma/SimSwap/commit/061329137d6d978d44ae2dc7c4700b825180c2ea?diff=unified) in the function arguments:

```diff
    def get(self, img, crop_size, max_num=0):
        bboxes, kpss = self.det_model.detect(img,
-                                            threshold=self.det_thresh,
                                             max_num=max_num,
                                             metric='default')
```

However:

1. In practice, [SimSwap uses the value of 0.6](https://github.com/woctezuma/SimSwap/blob/061329137d6d978d44ae2dc7c4700b825180c2ea/test_wholeimage_swapsingle.py#L56) rather than the default value of 0.5.

```python
    app = Face_detect_crop(name='antelope', root='./insightface_func/models')
    app.prepare(ctx_id= 0, det_thresh=0.6, det_size=(640,640),mode=mode)
```

2. I also [have to set `self.det_model.det_thresh`](https://github.com/woctezuma/SimSwap/commit/63306e70f11a123cd7c92db5611cab55377a51d4?diff=unified) instead of `self.det_thresh`.

```diff
    def prepare(self, ctx_id, det_thresh=0.5, det_size=(640, 640), mode ='None'):
-        self.det_thresh = det_thresh
+        self.det_model.det_thresh = det_thresh
```

Edit: Done! And I have sent a pull request to the official repository:
- https://github.com/neuralchen/SimSwap/pull/447
