### ISSUE TITLE
Problem with providers

### ISSUE THREAD

**Issue by fj44dn** [woctezuma/SimSwap-colab#16]
-------------- End ----------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-23-a8c0ee39c09a>](https://localhost:8080/#) in <cell line: 29>()
     27 
     28 
---> 29 app = Face_detect_crop(name='antelope', root='./insightface_func/models')
     30 app.prepare(ctx_id= 0, det_thresh=det_thresh, det_size=det_size, mode=mode)
     31 

5 frames
[/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py](https://localhost:8080/#) in _create_inference_session(self, providers, provider_options, disabled_optimizers)
    449         if not providers and len(available_providers) > 1:
    450             self.disable_fallback()
--> 451             raise ValueError(
    452                 f"This ORT build has {available_providers} enabled. "
    453                 "Since ORT 1.9, you are required to explicitly set "

ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by woctezuma** [comment]
I am sorry, but I cannot replicate this error on Google Colab.

![Picture](https://i.imgur.com/xoKJlfe.png)

**Comment by fj44dn** [comment]
Thanks problem solved
