### ISSUE TITLE
Issue with Simswap

### ISSUE THREAD

**Issue by nascacorp** [woctezuma/SimSwap-colab#19]
Hi ! get this error when i run it
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
moviepy 1.0.3 requires imageio<3.0,>=2.5; python_version >= "3.4", but you have imageio 2.4.1 which is incompatible.

**Comment by ActionStripes** [comment]
@ nasacorp:
I'm getting that message too, although I ignored it and was able to run the rest of the notebook anyway. Did you stop at that error, or keep going? The reason I ask is, I ran into a much nastier error later on in the "Run - Official code" section, concerning np.float. However, I found a workaround for that too, if you need it.

**Comment by woctezuma** [comment]
>
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages
> that are installed. This behaviour is the source of the following dependency conflicts.
> moviepy 1.0.3 requires imageio<3.0,>=2.5; python_version >= "3.4",
> but you have imageio 2.4.1 which is incompatible.
> ```
>

I doubt this is an actual issue in practice, and if it were, that would be solely the case for the application to **videos**.

That being said, I imagine we should be able to install a more recent version of `imageio` instead of:

```bash
!pip install imageio==2.4.1
```

> The reason I ask is, I ran into a much nastier error later on in the "Run - Official code" section, concerning np.float.

Right:
- https://github.com/woctezuma/SimSwap-colab/issues/20
