### ISSUE TITLE
Can swap specific attribute

### ISSUE THREAD

**Issue by rut00** [woctezuma/SimSwap-colab#2]
Hey, I was wondering if instead of the whole face only a specific attribute can be swapped? For eg, eyeglasses or a cap or something like that. 

I really appreciate any help you can provide.

**Comment by woctezuma** [comment]
This is not possible with my notebooks.

I have found related suggestions in the repository of the original code:
- https://github.com/neuralchen/SimSwap/issues/59
- https://github.com/neuralchen/SimSwap/issues/45
- https://github.com/neuralchen/SimSwap/issues/40
