### ISSUE TITLE
Simswap 512 (beta version) rendering

### ISSUE THREAD

**Issue by shukenmg** [woctezuma/SimSwap-colab#3]
https://github.com/neuralchen/SimSwap/issues/198#issuecomment-1046523358

The 512 model won't work unless that fix is applied.

**Comment by woctezuma** [comment]
For the notebook for images, I think this is taken care of because I call the official script `test_wholeimage_swapsingle.py` (or `test_wholeimage_swapmulti.py`) with the argument:
```bash
--crop_size 512
```

**Comment by woctezuma** [comment]
For the notebook for videos, I set:
```python
crop_size = 512
```
but I don't set
```python
opt.crop_size = 512
```

I will check if that matters. 👀 

References:
- https://github.com/neuralchen/SimSwap/issues/162
- https://github.com/neuralchen/SimSwap/issues/198

**Comment by woctezuma** [comment]
Alright, I have clarified my understanding at:
- https://github.com/neuralchen/SimSwap/issues/162#issuecomment-1152918418
- https://github.com/neuralchen/SimSwap/issues/198#issuecomment-1152921752

**Comment by woctezuma** [comment]
Thank you for the information! This should be fixed by:
- https://github.com/woctezuma/SimSwap-colab/commit/4e28e2c7248a248476c8edc4bbbc6eafcd0da436 `Fix use of beta model (#3)`

**Comment by shukenmg** [comment]
Very nice, thank you so much! :)
